[package]
name = "rivalnxt"
version = "0.10.3"
edition = "2021"
description = "Desktop shell for RivalNxt"
license = "MIT"
resolver = "2"

[build-dependencies]
tauri-build = { version = "2.5.0", features = [] }

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.9.0", features = [] }
tauri-plugin-shell = { version = "2.0.2", features = [] }
tauri-plugin-deep-link = "2"
tauri-plugin-single-instance = "2"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
tauri-plugin-dialog = "2.4.2"
tauri-plugin-updater = "2"
rfd = "0.15.4"
rust-ue-tools = { path = "./src/rust-ue-tools", features = ["pyo3"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[features]
default = ["custom-protocol"]
custom-protocol = []

[lints.rust]
non_snake_case = "allow"
dead_code = "allow"
unused_variables = "allow"
